### ISSUE TITLE
Maven repository is not working

### ISSUE THREAD

**Issue by santhosh-athreya** [gregwhitaker/roboto#2]
<dependency>
  <groupId>com.github.gregwhitaker</groupId>
  <artifactId>roboto-springboot</artifactId>
  <version>0.1.0</version>
  <type>pom</type>
</dependency>

Error: Missing artifact com.github.gregwhitaker:roboto-springboot:pom:0.1.0

**Comment by gregwhitaker** [comment]
Hmmmm. This works for me. 

It is currently hosted in bintray jcenter: [https://bintray.com/gregwhitaker/maven/roboto-springboot#files/com%2Fgithub%2Fgregwhitaker%2Froboto-springboot%2F0.1.0](https://bintray.com/gregwhitaker/maven/roboto-springboot#files/com%2Fgithub%2Fgregwhitaker%2Froboto-springboot%2F0.1.0)

Perhaps connectivity issues with jcenter? I have noticed it is very slow to resolve some dependencies lately.

**Comment by santhosh-athreya** [comment]
> Hmmmm. This works for me.
> 
> It is currently hosted in bintray jcenter: https://bintray.com/gregwhitaker/maven/roboto-springboot#files/com%2Fgithub%2Fgregwhitaker%2Froboto-springboot%2F0.1.0
> 
> Perhaps connectivity issues with jcenter? I have noticed it is very slow to resolve some dependencies lately.

Tried for different times. And I came across the same issue *artifact missing*. Any other solution?

**Comment by gregwhitaker** [comment]
You can temporarily download them from the jcenter site and install them in your maven local. I'll open a request to sync this with maven central which will hopefully fix the jcenter weirdness.
